# Generated by Django 3.1.7 on 2021-04-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20210404_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='sobre',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='cursos/imagens', verbose_name='Imagem'),
        ),
        migrations.AlterModelTable(
            name='cursos',
            table='tb_mooc_cursos',
        ),
    ]
