# Generated by Django 3.1.7 on 2021-05-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20210408_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data Inicio'),
        ),
    ]
